name: Merge y Push

on: 
  push:
    branches:
      - 'development'  # Esta es la rama que activará la acción al hacer push

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Realizar el merge de development en main
        uses: morbalint/git-merge-action@v1
        with:
          target: 'main'  # Rama destino
          source: 'development'  # Rama origen
          strategy_options: 'ours'  # Estrategia de fusión (puedes personalizarla)
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub para autenticación
