name: Merge y Push

on:
  push:
    branches:
      - 'development'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Realizar el merge de development en main
        uses: morbalint/git-merge-action@v1
        with:
          target: 'main'
          source: 'development'
          strategy_options: 'ours'
          token: ${{ secrets.GITHUB_TOKEN }}  # Esto usa el token predeterminado de GitHub Actions

